name: CI

on:
    push:
        branches: ["main"]
        paths:
            - "web-app/**"
    pull_request:
        paths:
            - "web-app/**"

jobs:
    test-backend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.13

            - name: Install backend Python packages
              working-directory: ./web-app
              run: |
                  pip install -e ".[dev]"

            - name: Run pytest
              working-directory: ./web-app
              run: |
                  pytest --maxfail=1 --disable-warnings -q
